name: 'Terraform'
 
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
 
jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VERSION: 1.5.7
    runs-on: self-hosted
    # environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # defaults:
    #   run:
    #     shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2            
      
  #   - name: HashiCorp - Setup Terraform
  # # You may pin to the exact commit or the version.
  # # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
  #     uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan -input=false

    - name: Terraform apply
      run: terraform apply -input=false -auto-approve
          
    
